#!/usr/bin/env bash
# SWARM Messenger — generate this deployment's staging secrets and .env values.
#
# Writes (all git-ignored):
#   staging-secrets.yml     the secrets bundle the server reads
#   .env                    the compose environment, including the public halves
#   certs/*                 the internal CA and the registration stub certificate
#
# Refuses to overwrite anything that already exists: rotating the zk secrets or the
# sealed-sender trust root invalidates credentials clients already hold.
#
# Requirements on the host: bash, openssl, python3, and a JDK 26 plus the built jar
#   ./mvnw -DskipTests -Pexclude-spam-filter package
# The jar is needed for the server's own `zkparams` and `certificate` commands, which are the
# only correct way to produce zk parameters and a sealed-sender certificate — they call
# libsignal. Nothing here invents cryptography.
#
# Usage:
#   ./generate-secrets.sh [path/to/TextSecureServer-<version>.jar]

set -euo pipefail

cd "$(dirname "$0")"

JAR="${1:-$(ls ../../service/target/TextSecureServer-*.jar 2>/dev/null | grep -v -- '-tests\.jar$' | grep -v '^.*original-' | head -1)}"

die() { printf '%s\n' "$*" >&2; exit 1; }

[ -n "${JAR}" ] && [ -f "${JAR}" ] || die "Cannot find the server jar. Build it with:
  ./mvnw -DskipTests -Pexclude-spam-filter package
then pass the path: ./generate-secrets.sh path/to/TextSecureServer-<version>.jar"

command -v openssl >/dev/null || die "openssl is required"
command -v python3 >/dev/null || die "python3 is required"
command -v java >/dev/null || die "java (26+) is required"

[ -e staging-secrets.yml ] && die "staging-secrets.yml already exists. Move it aside first — regenerating invalidates credentials clients already hold."
[ -e .env ] && die ".env already exists. Move it aside first."

rand_b64_32() { openssl rand -base64 32 | tr -d '\n'; }

echo "==> 1/6  internal CA and registration-stub certificate"
./certs/make-certs.sh >/dev/null
CA_PEM_ONELINE="$(python3 - <<'PY'
with open("certs/swarm-staging-ca.crt", "r", encoding="ascii") as fh:
    print(fh.read().replace("\n", "\\n"), end="")
PY
)"

echo "==> 2/6  random shared secrets"
AWS_KEY="swarm$(openssl rand -hex 8)"
AWS_SECRET="$(rand_b64_32)"
CDN_KEY="swarmcdn$(openssl rand -hex 4)"
CDN_SECRET="$(rand_b64_32)"
MINIO_ROOT_PASSWORD="$(rand_b64_32)"

echo "==> 3/6  throwaway RSA key for the two disabled Google integrations"
# gcpAttachments and FCM are off, but the server parses these keys at startup, so they must be
# syntactically valid. Generated fresh so no published test key ends up in this deployment.
THROWAWAY_RSA="$(openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:2048 2>/dev/null)"
THROWAWAY_RSA_INDENTED="$(printf '%s\n' "${THROWAWAY_RSA}" | sed 's/^/  /')"

echo "==> 4/6  zk parameters (four independent sets, via the server's zkparams command)"
# `initialize()` demands the secrets-bundle property even for a command that never reads it.
TMP_BUNDLE="$(mktemp)"
trap 'rm -f "${TMP_BUNDLE}"' EXIT
printf 'placeholder: unset\n' > "${TMP_BUNDLE}"

zkparams() {
  java -Dsecrets.bundle.filename="${TMP_BUNDLE}" -jar "${JAR}" zkparams
}

read_pair() {
  local out; out="$(zkparams)"
  ZK_PUBLIC="$(printf '%s\n' "${out}" | sed -n 's/^Public: //p')"
  ZK_PRIVATE="$(printf '%s\n' "${out}" | sed -n 's/^Private: //p')"
  [ -n "${ZK_PUBLIC}" ] && [ -n "${ZK_PRIVATE}" ] || die "zkparams produced no output"
}

read_pair; GROUPS_PUBLIC="${ZK_PUBLIC}"; GROUPS_SECRET="${ZK_PRIVATE}"
read_pair; CHAT_SECRET="${ZK_PRIVATE}"
read_pair; CALLING_SECRET="${ZK_PRIVATE}"
read_pair; CALLING_PRE_SECRET="${ZK_PRIVATE}"

echo "==> 5/6  sealed-sender trust root and server certificate"
CA_OUT="$(java -Dsecrets.bundle.filename="${TMP_BUNDLE}" -jar "${JAR}" certificate --ca)"
UD_ROOT_PUBLIC="$(printf '%s\n' "${CA_OUT}" | sed -n 's/^Public key *: //p')"
UD_ROOT_PRIVATE="$(printf '%s\n' "${CA_OUT}" | sed -n 's/^Private key: //p')"
[ -n "${UD_ROOT_PRIVATE}" ] || die "certificate --ca produced no output"

CERT_ID="$(( (RANDOM << 15 | RANDOM) % 1000000 + 1 ))"
CERT_OUT="$(java -Dsecrets.bundle.filename="${TMP_BUNDLE}" -jar "${JAR}" certificate \
  --key "${UD_ROOT_PRIVATE}" --id "${CERT_ID}")"
UD_CERTIFICATE="$(printf '%s\n' "${CERT_OUT}" | sed -n 's/^Certificate: //p')"
UD_PRIVATE_KEY="$(printf '%s\n' "${CERT_OUT}" | sed -n 's/^Private key: //p')"
[ -n "${UD_CERTIFICATE}" ] || die "certificate command produced no certificate; run it by hand:
  java -Dsecrets.bundle.filename=<bundle> -jar ${JAR} certificate --key <root private key> --id <id>"

echo "==> 6/6  writing staging-secrets.yml and .env"

umask 077

cat > staging-secrets.yml <<YAML
# SWARM Messenger staging secrets — GENERATED by generate-secrets.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# NOT IN GIT. Back this file up off the host: the zk secrets and the sealed-sender trust root
# cannot be rotated without updating every client.

aws.accessKeyId: ${AWS_KEY}
aws.secretAccessKey: ${AWS_SECRET}

cdn.accessKey: ${CDN_KEY}
cdn.accessSecret: ${CDN_SECRET}

groupsZkConfig.serverSecret: ${GROUPS_SECRET}
chatZkConfig.serverSecret: ${CHAT_SECRET}
callingZkConfigV101.serverSecret: ${CALLING_SECRET}
callingZkConfigPreV101.serverSecret: ${CALLING_PRE_SECRET}

# Sealed-sender trust root. The clients must ship ${UD_ROOT_PUBLIC} as their serverTrustRoot.
unidentifiedDelivery.privateKey: ${UD_PRIVATE_KEY}

foundationDbMessages.versionstampCipherKey.0: $(rand_b64_32)
registrationService.collationKeySalt: $(rand_b64_32)
registrationWebAuthn.userHandleBlindingSecret: $(rand_b64_32)
linkDevice.secret: $(rand_b64_32)
storageService.userAuthenticationTokenSharedSecret: $(rand_b64_32)
paymentsService.userAuthenticationTokenSharedSecret: $(rand_b64_32)
directoryV2.client.userAuthenticationTokenSharedSecret: $(rand_b64_32)
directoryV2.client.userIdTokenSharedSecret: $(rand_b64_32)
svr2.userAuthenticationTokenSharedSecret: $(rand_b64_32)
svr2.userIdTokenSharedSecret: $(rand_b64_32)
svrb.userAuthenticationTokenSharedSecret: $(rand_b64_32)
svrb.userIdTokenSharedSecret: $(rand_b64_32)
tus.userAuthenticationTokenSharedSecret: $(rand_b64_32)

tlsKeyStore.password: $(rand_b64_32)

# ---- placeholders for features that are OFF (see docs/STAGING.md) --------------------
stripe.apiKey: unset
stripe.idempotencyKeyGenerator: $(rand_b64_32)
braintree.publicKey: unset
braintree.privateKey: unset
cdn3StorageManager.clientSecret: unset
turn.cloudflare.apiToken: unset
paymentsService.fixerApiKey: unset
paymentsService.coinGeckoApiKey: unset
hlrLookup.apiKey: unset
hlrLookup.apiSecret: unset

apn.teamId: disabled
apn.keyId: disabled
apn.signingKey: |
$(openssl genpkey -algorithm EC -pkeyopt ec_paramgen_curve:P-256 2>/dev/null | sed 's/^/  /')

appleAppStore.encodedKey: |
$(openssl genpkey -algorithm EC -pkeyopt ec_paramgen_curve:P-256 2>/dev/null | sed 's/^/  /')

keyTransparencyService.clientPrivateKey: |
$(openssl genpkey -algorithm EC -pkeyopt ec_paramgen_curve:P-256 2>/dev/null | sed 's/^/  /')

gcpAttachments.rsaSigningKey: |
${THROWAWAY_RSA_INDENTED}

fcm.credentials: |
  { "type": "service_account", "client_id": "disabled", "client_email": "disabled@swarm.invalid",
    "private_key_id": "disabled",
    "private_key": "$(printf '%s\n' "${THROWAWAY_RSA}" | python3 -c 'import sys; sys.stdout.write(sys.stdin.read().rstrip("\n").replace(chr(10), "\\n"))')" }
YAML

cat > .env <<ENV
# SWARM Messenger staging environment — GENERATED by generate-secrets.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# NOT IN GIT.

SWARM_STAGING_FIXED_CODE=true
SWARM_STAGING_VERIFICATION_CODE=123456

SWARM_CHAT_DOMAIN=chat.swarm.green
SWARM_CDN_DOMAIN=cdn.chat.swarm.green
SWARM_REG_DOMAIN=reg.chat.swarm.green
SWARM_SFU_DOMAIN=sfu.chat.swarm.green
SWARM_ACME_EMAIL=REPLACE_ME_BEFORE_STARTING_CADDY

SWARM_AWS_REGION=us-east-1
SWARM_AWS_ACCESS_KEY_ID=${AWS_KEY}
SWARM_AWS_SECRET_ACCESS_KEY=${AWS_SECRET}

SWARM_MINIO_ROOT_USER=swarmstaging
SWARM_MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
SWARM_CDN_ACCESS_KEY=${CDN_KEY}
SWARM_CDN_SECRET_KEY=${CDN_SECRET}

SWARM_REGISTRATION_CA_PEM=${CA_PEM_ONELINE}
SWARM_GROUPS_ZK_SERVER_PUBLIC=${GROUPS_PUBLIC}
SWARM_UNIDENTIFIED_DELIVERY_CERTIFICATE=${UD_CERTIFICATE}

SWARM_LOG_LEVEL=INFO
SWARM_TABLE_PREFIX=swarm_
SWARM_CDN_BUCKET=swarm-cdn
SWARM_PREKEY_BUCKET=swarm-prekeys
SWARM_CONFIG_BUCKET=swarm-config
ENV

chmod 600 staging-secrets.yml .env

cat <<EOF

==> done

  staging-secrets.yml   $(wc -l < staging-secrets.yml) lines, mode 600
  .env                  $(wc -l < .env) lines, mode 600
  certs/                internal CA + registration-stub certificate

NEXT
  1. Set SWARM_ACME_EMAIL in .env before starting the caddy profile.
  2. Give the SWARM Messenger clients this sealed-sender trust root (serverTrustRoot):

       ${UD_ROOT_PUBLIC}

     Nothing else needs it, and the private half is only in staging-secrets.yml.
  3. Back up staging-secrets.yml and certs/ somewhere off this host.
  4. docker compose up -d   (see docs/STAGING.md for start order and health checks)
EOF
